# Generated by Django 3.1.2 on 2020-10-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('temperature', models.IntegerField()),
                ('company', models.CharField(max_length=200)),
                ('identification_number', models.CharField(blank=True, max_length=200)),
                ('telephone_number', models.IntegerField()),
                ('date', models.DateField(verbose_name='date recorded')),
            ],
        ),
    ]
