# Generated by Django 3.1.2 on 2020-10-27 07:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_auto_20201026_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitors',
            name='temperature',
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.visitors')),
            ],
        ),
    ]
