# Generated by Django 3.1.2 on 2020-10-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0006_auto_20201027_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
