# Generated by Django 3.1.2 on 2020-10-27 08:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0003_auto_20201027_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
