# Generated by Django 3.1.2 on 2020-10-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0005_auto_20201027_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='register_date'),
        ),
    ]
