# Generated by Django 3.1.2 on 2020-10-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0007_auto_20201027_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='telephone_number',
            field=models.CharField(max_length=100),
        ),
    ]
